### ISSUE TITLE
CLR normalisation across features or cells?

### ISSUE THREAD

**Issue by danmoore1987** [SydneyBioX/CiteFuse#10]
Dear CiteFuse team,

Great package! Works really well. I also really appreciate all the effort put into making an entire suite of visiualisation tools as well! They are pretty neat.

I have a question on CLR normailsation, is it across features or cells? 

Thank you!

**Comment by friedue** [comment]
```
.clr <- function(X) {

    X[X == 0] <- min(X[X != 0])
    logX <- log(X)
    logSet <- logX[, seq_len(ncol(X)), drop = FALSE]
    ref <- Matrix::rowMeans(logSet)
    res <- sweep(logX, 1, ref, "-")

    return(res)
}
```

This is what the code for `.clr()` says. Seems to be done across rows, i.e. features.

**Comment by HaniJieunKim** [comment]
Hi danmoore, 

Apologies for getting back to you late! As friedue as pointed out, CLR transformation is performed across rows (genes as our features).
