### ISSUE TITLE
Louvain clustering: choosing resolution

### ISSUE THREAD

**Issue by ghost** [SydneyBioX/CiteFuse#11]
Hi,

I am using the function igraphClustering to perform clustering using "louvain" method. I am wondering, is there a way to change the resolution? When overlaying the ADTs on the embedding, I can clearly see that one cluster is a combination of, what should be, two separate clusters. I would like to increase the resolution in order to capture those two clusters separately. TIA.

**Comment by HaniJieunKim** [comment]
Hi @aalajami,

Thanks for your interest in CiteFuse! You can change the resolution by adding the argument `resolution`. 

`SNF_W_louvain <- igraphClustering(sce_citeseq, method = "louvain", resolution = 3)`

Hani
