### ISSUE TITLE
Contributing to the OSCA book

### ISSUE THREAD

**Issue by LTLA** [SydneyBioX/CiteFuse#12]
Seems like this package could have several appearances in the OSCA book - the demultiplexing section of the droplet processing, the integrated protein abundance chapter, the doublet detection chapter. Would contributing to the book be of interest?

**Comment by HaniJieunKim** [comment]
Hi Aaron,

CiteFuse would be a great addition to OSCA! Thank you for getting in touch!

Please let us know how we should proceed to contribute towards the chapters. You can contact us at hani.kim@sydney.edu.au and yingxin.lin@sydney.edu.au. 

Best regards,

Hani & Yingxin

**Comment by LTLA** [comment]
Okay, great. We're currently fragmenting the book to make it more modular and easier to contribute to. I'll revisit this once the fragmentation is complete; you may also wish to have a look at the book and see where you would like to add material.
