### ISSUE TITLE
Using CiteFuse with MissionBio data

### ISSUE THREAD

**Issue by mcortes-lopez** [SydneyBioX/CiteFuse#16]
Hi,
I was wondering if is possible use CiteFuse with MissionBio data (Protein + DNA)? I tried using my normalized ADT values, however, given that MissionBio does not have RNA, I do not know how can I bypass this requirement for some of the functions. I would like to use the ADT importance feature as well as perform between sample analysis using a CITE-Seq reference. 
Thanks!

**Comment by HaniJieunKim** [comment]
Hi @mcortes-lopez 

Many thanks for your interest! 

You can perform the ADT importance feature by using the [importanceADT](https://github.com/SydneyBioX/CiteFuse/blob/master/R/importanceADT.R) on your ADT matrix as long as you provide the cell type labels, bypassing the integration step.
