### ISSUE TITLE
UMAP/tSNE expression plots

### ISSUE THREAD

**Issue by shivarice** [SydneyBioX/CiteFuse#2]
![image](https://user-images.githubusercontent.com/22628700/76465480-06f1e280-63b4-11ea-9d6e-c24641c735dc.png)

I was on your shiny website and I was curious how would I be able to make these plots via R.

**Comment by YingxinLin** [comment]
Hi,

Thank you for your interest in CiteFuse.

In our latest version, we have implemented the function ` visualiseDim` that allows to plot the UMAP coloured by expression from different assays and alternative expression. Please install the latest package, and check out our vignette https://sydneybiox.github.io/CiteFuse/articles/CiteFuse.html#visualisation section.

Cheers,
Yingxin

**Comment by shivarice** [comment]
Will do thanks!
