### ISSUE TITLE
Docker Image Available?

### ISSUE THREAD

**Issue by Jennifer-Foltz** [SydneyBioX/CiteFuse#4]
Good morning!

I'm very excited to try CITE-fuse, but I don't have R version 4.0 installed locally yet, and when I install I get this message: `ERROR: this R is version 3.6.2, package 'CiteFuse' requires R >= 4.0 ` Do you have plans to create a docker image for CITE-fuse, or know of one available that I could use?

Thanks!

Jennifer

**Comment by YingxinLin** [comment]
Hi Jennifer,

We haven't had a docker image for CiteFuse yet. But if you want to install CiteFuse in R3.6, you could install the older version of CiteFuse (v0.99.4) via
`devtools::install_github("SydneyBioX/CiteFuse@a86bba3")`

Best wishes,
Yingxin

**Comment by Jennifer-Foltz** [comment]
Thank you @YingxinLin !  What features are different between the old and new version of CiteFuse?

**Comment by YingxinLin** [comment]
Hi! 

Mainly it is in `CiteFuse()`, where more parameter inputs are added and also the coding styles are improved for bioconductor submission.

Yingxin

**Comment by Jennifer-Foltz** [comment]
@YingxinLin Thank you!  What CiteFuse parameter inputs have been added?

**Comment by YingxinLin** [comment]
In `CiteFuse()` the following parameters related to similarity network fusion `SNF()` are added:
`K_knn_Aff` and `sigma`. And also the highly variable feature selection related to `modelGeneVar ` in `scran` package: `FDR` and `bio`.

Yingxin

**Comment by DarioS** [comment]
Before we get ahead of ourselves, what is preventing you from installing R version 4?

**Comment by Jennifer-Foltz** [comment]
Thanks @YingxinLin !  

@DarioS , I haven't updated to R v4. yet because I'm concerned about other packages I frequently use not working properly in R v4.

**Comment by Jennifer-Foltz** [comment]
On another note, how is the `meanDiff` calculated in `DEgenes`?  I installed the devtools CiteFuse version and noticed that `meanDiff` isn't the same value as manually subtracting meanExprs.1 from mean.Exprs.2, and so far seems to be the same value as the pctDiff, and am trying to understand this as I use the `selectDEgenes` function to choose genes to plot.

Thank you!

**Comment by DarioS** [comment]
A docker image of Bioconductor, which CiteFuse is part of, and R version 4.0.0 is available, according to [the recent announcement by the Bioconductor management team](https://stat.ethz.ch/pipermail/bioc-devel/2020-May/016774.html).

**Comment by Jennifer-Foltz** [comment]
This is wonderful!!  Thank you @DarioS !

**Comment by YingxinLin** [comment]
Hi @JenniferWUSTL , 

Thank you very much for pointing out the bugs in DEgenes function! There is indeed a typo in the codes. You are right, meanDiff should be the same value as manually subtracting meanExprs.1 from mean.Exprs.2. I have just push the fixed version in the latest GitHub version. 

Best,
Yingxin
