### ISSUE TITLE
clr transformation for ADT

### ISSUE THREAD

**Issue by joonlee3** [SydneyBioX/CiteFuse#5]
Hi,

I was trying to use **clr** transformation for ADT. I've got the following message after running CiteFuse **normaliseExprs** with **clr** option.

```
> sce_citeseq.1 <- normaliseExprs(sce_citeseq.1, altExp_name = "ADT", transform = "clr")
<sparse>[ <logic> ] : .M.sub.i.logical() maybe inefficient
```

   Can I ignore the message? Please let me know. Thanks.

Best,
Joon

**Comment by YingxinLin** [comment]
Hi Joon,

I am trying to reproduce this message. May I check what is the class of the ADT matrix object, and what is the dimension of the matrix?

Thank you,
Yingxin

**Comment by joonlee3** [comment]
Hi Yingxin,

The class is 'dgCMatrix.' The dims of ADT and RNA are 273 x 13061 & 17450 x 13061.

I ran 'CiteFuse' command by using log-transformation yesterday. It is still performing SNF.

I am wondering how you deal with a dataset with 10K - 60K cells. If you have any suggestions, please let me know. Thank you.

Best,
Joon

**Comment by YingxinLin** [comment]
Hi Joon,

Thank you for your information. I will have a look at the current clr function.

For the SNF part, it uses `propr` function to calculate the dissimilarity matrix for ADT, taking the input of counts. So clr function won't effect SNF functionality. 

Indeed, the current SNF function may take a long time for big matrix, and we are looking into different methods to speed it up. You may consider to test it on a smaller subset data first. We will let you know if we have any updates in speeding the function up.

Cheers,
Yingxin

**Comment by bio-la** [comment]
Hi, I'm also interested in this. have you guys run simulations on what number of cells will likely start causing problems? I'm running 14k cells matrix and no problems so far but I have a huge dataset coming soon so was hoping you could help with that?

many thanks!

**Comment by sorjuela** [comment]
Hi, I get the same message with ` transform = "clr"`. But `as.matrix()` on the counts solved the problem.
