### ISSUE TITLE
Batch Correction Advice

### ISSUE THREAD

**Issue by Jennifer-Foltz** [SydneyBioX/CiteFuse#7]
Good morning!

I really like CiteFuse and have found some interesting results on my datasets!  I would like to now combine data across different batches that have clear batch effects.  Have you tried any batch correction with CiteFuse to combine data like this? Any tips or suggestions would be greatly appreciated!

Thank you for your work!!

**Comment by YingxinLin** [comment]
Hi,

Thank you for your interest in CiteFuse and it's great to know that CiteFuse helps your analysis!

For performing CiteFuse with batch effect, I will suggest you could probably try the following:

1. Perform some single cell batch correction methods on RNA and ADT respectively, and then calculate distance based on batch corrected matrices as input of CiteFuse. Some useful codes will be following

```
# integrated_ADT, integrated_RNA as batch corrected matrix (or batch corrected reduced dimension)
dist_adt <- 1 - as.matrix(cor(integrated_ADT))
dist_rna <- 1 - as.matrix(cor(integrated_RNA))

W1 <- SNFtool::affinityMatrix(dist_adt, K = 30, sigma = 0.45)
W2 <- SNFtool::affinityMatrix(dist_rna, K = 30, sigma = 0.45)

sce_citeseq <- CiteFuse(sce_citeseq, W_list = list(W1, W2))
```

2. To check whether the batch correction + CiteFuse makes sense, you could also perform CiteFuse and identify clusters within each batch, and see how the clusters from different batches align.

Please feel free to let me know if you have any other further questions about CiteFuse.

Best wishes,
Yingxin
