### ISSUE TITLE
Working with pre-normalized CITE data from other tools

### ISSUE THREAD

**Issue by nbartonicek** [SydneyBioX/CiteFuse#8]
Good day,
Thank you for making CiteFuse, it's already working great for us!

We wanted to use previously cleaned and denoised data (https://mattpm.github.io/dsb/) and combine it with the CiteFuse pipeline. What would be the easiest way to bypass normalisation from CiteFuse, and just use data normalised from other sources?

Cheers,
Nenad Bartonicek, PhD
Bioinformatic Officer
Centre for Clinical Genomics
Garvan Institute of Medical Research
384 Victoria Street
Sydney NSW 2010 
Australia

**Comment by YingxinLin** [comment]
Hi Nenad,

Thank you for your interest in CiteFuse! And it is great to hear that it works well in your data.

The easiest way currently is to derive the affinity matrices as input of `CiteFuse`. The example codes to do so are as follow:

```
# normalised_ADT, normalised_RNA as normalised matrix (some other distance metrics can be used as well)
dist_adt <- 1 - as.matrix(cor(normalised_ADT))
dist_rna <- 1 - as.matrix(cor(normalised_RNA))

W1 <- SNFtool::affinityMatrix(dist_adt, K = 30, sigma = 0.45)
W2 <- SNFtool::affinityMatrix(dist_rna, K = 30, sigma = 0.45)

sce_citeseq <- CiteFuse(sce_citeseq, W_list = list(W1, W2))
```

We will try to incorporate the denoised function in our future version.

Please feel free to let me know if you have any further questions about CiteFuse.

Best wishes,
Yingxin

**Comment by DM0815** [comment]
> st_rna <- 1 - as.matrix(cor(normalised_RNA))

Excuse me. I have a question.  In you code,last row,in CiteFuse(sce_citeseq, W_list = list(W1, W2)) , the sce_citeseq is not to be defined, how do you use it?
