### ISSUE TITLE
Apply CiteFuse on 10x feature barcoding data without HTO

### ISSUE THREAD

**Issue by lxhuang7** [SydneyBioX/CiteFuse#9]
Hi, thanks for this wonderful package! I would like to test it on a dataset (single sample) generated by 10x Genomic feature barcoding that does not have HTO data. However, it seems HTO data matrix is required in several functions. Is there a way to bypass the HTO data? Thanks.

**Comment by YingxinLin** [comment]
Hi,

Thank you for your interest of our package!

HTO data is only used in the doublet detection.

You can definitely bypass it and perform the downstream analysis.

Yingxin
